#remote_theme: beAuthentic/askclass-course-theme
theme: askclass-course-theme

title: "Kairos Church History II"
description: >
  This is a survey of the history of the church from the Reformation to the modern church.
  This course will give students a broad and practical view of the church and our heritage as
  Protestants. We will appreciate the growth of the church, its struggles, and the highs and
  lows of an exceptionally long story.

acc:
  date_format: "%b %d, %y"
  short_name: "CH-526"
  color:
    theme: "#2cdd88"
    bg: "#2a2a2a"
  url: "https://ch526.nissi.app"
  categories:
    - education
  logo:
    image: "logo.svg"
    size: 70
    height: 70
    alt_image: "logo.svg"
    alt_size: 200
    sizes: [ 48, 96, 144, 192, 300, 512, 800, 1024 ]
  shortcuts:
    - name: Syllabus
      url: https://ch526.nissi.app/session/syllabus
      desc: Class syllabus and contact information
  meta:
    apple_icon: "logo-square-300.png"
    og_image: "logo-square-512.png"
    shortcut:
      favicon: "favicon.ico"
      type: "image/png"
      image: "logo-96.png"
    keywords: >
      education,
      learning,
      theology,
      psychology,
      christianity
  footer:
    - icon: "school"
      href: "http://kairos.aeu.edu/"
      text: "Kairos University"
    - icon: "attribution"
      href: "https://acc.askclass.com"
      text: "AskClass Template"
  # Donot change the below (will figure something out later)
  font_families:
    - Teko
    - Open+Sans:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,700
    - Josefin+Sans
    - Lexend
    - Share+Tech+Mono
    - Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200

collections_dir: content
collections:
  session:
    output: true
  segment:
    output: true

defaults:
  - scope:
      path: "*.html"
    values:
      layout: "default"
  - scope:
      type: "session"
    values:
      layout: "session"
  - scope:
      type: "segment"
    values:
      layout: "segment"

exclude:
  - CNAME
  - runme.sh
